runtime: python38
entrypoint: gunicorn -b :$PORT index:app

env_variables:
  OPENAI_API_KEY : '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'
  TOKEN : 'EAADWtKt4LVMBAJ9zRISN942X6W9ZA6jNixSamfXcjsUxkhIfjzoHAmJTImjAGFwjZBgUkOVmZAcspmZB4KBCxWcPPLNzz6LkBYGXzO9JmMR5kPYy5XszweoViqgxO87mCZAMhvqHRRMv5j1Igtjd5gWoXfD94nHjclr2HV7VxSJaOlnubHVeBdgzFANkBTQNbhP327lC1rkXZBo4jXO7WN'
  MYTOKEN : 'asif'